# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs
name: Build
on:
 pull_request:
   branches:
     - master
jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 
      - uses: isbang/compose-action@v1.4.1
        with:
          compose-file: "docker-compose.yml"
          down-flags: "--volumes"
          services: |
            postgres
      - name: Install dependencies
        run: npm install 
      - name: Set-up istanbul
        run: npm i istanbul
      - name: Test and coverage
        run: npm test
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets. SONARCLOUD_TOKEN }}
